### ISSUE TITLE
QA PyWb resolving to /null

### ISSUE THREAD

**Issue by crarugal** [ukwa/ukwa-pywb#63]
Recently, in the past two weeks or so in QA PyWb, I've noticed many sites that resolve to a non-existent /null

https://www.webarchive.org.uk/act/wayback/archive/20210321105502/http://www.westyorkshire-pcc.gov.uk/news-events/news/west-yorkshire-pcc-statement-after-home-office-announcement-ps1305m-tackle-serious-violence-murder-and-knife-crime

Screenshot of redirect
![image](https://user-images.githubusercontent.com/18530934/112852471-e28ea400-90a3-11eb-9590-82720b264c1b.png)

When loading the site it seems fine, and starts to render well, but then will eventually redirect to /null

- https://www.webarchive.org.uk/act/wayback/archive/20210321105502/http://www.westyorkshire-pcc.gov.uk/news-events/news/west-yorkshire-pcc-statement-after-home-office-announcement-ps1305m-tackle-serious-violence-murder-and-knife-crime

- site starts to render in browser
![image](https://user-images.githubusercontent.com/18530934/112856391-a6f5d900-90a7-11eb-8745-3d9a84599f16.png)

- then PyWb tries is redirected to http://www.westyorkshire-pcc.gov.uk/news-events/news/null
- ![image](https://user-images.githubusercontent.com/18530934/112852471-e28ea400-90a3-11eb-9590-82720b264c1b.png)

-  Even though the original page was http://www.westyorkshire-pcc.gov.uk/news-events/news/west-yorkshire-pcc-statement-after-home-office-announcement-ps1305m-tackle-serious-violence-murder-and-knife-crime

This seems to be when the redirect occurs: 
![image](https://user-images.githubusercontent.com/18530934/112853398-b6bfee00-90a4-11eb-8fdd-136abc2b63f3.png)

![image](https://user-images.githubusercontent.com/18530934/112854062-5ed5b700-90a5-11eb-85a4-c50e417eea27.png)

It doesn't seem to be effecting Open Access PyWb of the same instance: https://www.webarchive.org.uk/wayback/archive/20210321105502/http://www.westyorkshire-pcc.gov.uk/news-events/news/west-yorkshire-pcc-statement-after-home-office-announcement-ps1305m-tackle-serious-violence-murder-and-knife-crime

so it looks like an issue with QA PyWb.

screenshot of Open Access PyWb
![image](https://user-images.githubusercontent.com/18530934/112854548-e02d4980-90a5-11eb-84e4-b4d3ec37c6ea.png)

Other instances where this has occurred in QA PyWb:
•	https://www.webarchive.org.uk/act/wayback/archive/20210318114211/http://www.westyorkshire-pcc.gov.uk/
•	https://www.webarchive.org.uk/act/wayback/archive/20210324100516/http://www.qehkl.nhs.uk/

Other behaviour I've recently noticed, though not necessarily related:

- having to constantly log into ACT, this was never an issue and I could move between tabs or open new tabs, but now I seem to be prompted with almost every new tab/window
- 
![image](https://user-images.githubusercontent.com/18530934/112858055-68f9b480-90a9-11eb-83f9-31f1b14e7004.png)

- 502 Bad Gateway seems to happen more frequently, perhaps at least once or twice a day, but then is resolved within a few minutes
![image](https://user-images.githubusercontent.com/18530934/112857937-48315f00-90a9-11eb-9a11-e9bb48e998c2.png)

**Comment by crarugal** [comment]
Another issue that seems to occur after rendering, though I'm unsure if it is related:
https://www.webarchive.org.uk/act/wayback/archive/20210224181126/https://yougov.co.uk/topics/health/articles-reports/2021/02/23/brits-ditching-bras-showering-less-lockdown

Error 
![image](https://user-images.githubusercontent.com/18530934/113027155-adf11a00-9181-11eb-99ce-6e1c4b8560a2.png)


Where it occurs:
![image](https://user-images.githubusercontent.com/18530934/113027259-c6f9cb00-9181-11eb-8d59-673fcc48e010.png)

**Comment by anjackson** [comment]
This seems to be very weird. I've tracked the URC Our Work example down to this file:

https://www.webarchive.org.uk/act/wayback/archive/20210305095213js_/https://w.sharethis.com/button/buttons.js

If you look closely, you can see PyWB has re-written the JavaScript, containing bits like `stlib.data.pageInfo.WB_wombat_location="ERROR"`

But on DEV, (for those who have access), the modifications from PyWB are totally different:

https://dev.webarchive.org.uk/act/wayback/archive/20210305095213js_/https://w.sharethis.com/button/buttons.js

That version has a big insert at the top, like:

```
var _____WB$wombat$assign$function_____ = function(name) {return (self._wb_wombat && self._wb_wombat.local_init && self._wb_wombat.local_init(name)) || self[name]; };
if (!self.__WB_pmw) { self.__WB_pmw = function(obj) { this.__WB_source = obj; return this; } }
{
let window = _____WB$wombat$assign$function_____("window");
let self = _____WB$wombat$assign$function_____("self");
let document = _____WB$wombat$assign$function_____("document");
let location = _____WB$wombat$assign$function_____("location");
let top = _____WB$wombat$assign$function_____("top");
let parent = _____WB$wombat$assign$function_____("parent");
let frames = _____WB$wombat$assign$function_____("frames");
let opener = _____WB$wombat$assign$function_____("opener");
```

And it does not rewrite the body, e.g. it has `stlib.data.pageInfo.location="ERROR"` instead of the modified version above.

All this would seem to indicate that the PROD service is running an older version of PyWB than DEV. But according to Docker they are both running `ukwa/ukwa-pywb:2.5.x-beta`!

If that's the case, then I guess there's some caching somewhere? Except I can _see_ the hit in the log files of the PyWB instance. And if I `exec` into that container, I can see it is running `pywb 2.5.0`. And the same is true for DEV.

The two services are deployed slightly differently, in terms of UWSGI/NGINX configuration and proxying. Hey @ikreymer are you aware of anything that would change how JavaScript re-writing is done?

**Comment by crarugal** [comment]
Similar issue, but just another example of possible re-writing:

https://www.webarchive.org.uk/act/wayback/archive/20210304120712/https://www.eventbrite.co.uk/
![image](https://user-images.githubusercontent.com/18530934/114205056-d03d2180-9951-11eb-9831-dec745c8b8ba.png)

**Comment by ikreymer** [comment]
Sorry for late response, but I can confirm that the latest version is with the big insert at the top and not rewriting location to WB_wombat_location. The version that has that must be out of date, and so a lot of rewriting probably isn't working correctly.
It looks like the production version is up-to-date as well, although many files are for internal access only (451 errors) but it does appear to be doing the right thing.
I don't have access to the /act/ versions so can't check those, but hopefully upgrading to the latest 2.5.0 image fixes many of these issues?

**Comment by anjackson** [comment]
Oh well, this was fun.

So.

The thing is, current production QA Wayback is deployed behind an authenticating proxy I hacked together. It's [written in Java and is horrid](https://github.com/ukwa/w3act/blob/6ad35fff95854edd847c279904534938ff73295d/app/controllers/WaybackController.java#L64). This code does not pass the `User-Agent` header along, and PyWB checks the User Agent before deciding whether to proxy the JS objects.

As this would e.g. mess with POST requests, I've already been working on doing this in more sensible way, see https://github.com/ukwa/w3act/issues/655 and this is what is deployed on DEV, which is why it works fine.

So, the solution is to hurry up and get the new stack deployed!

**Comment by ikreymer** [comment]
Nice find! I totally forgot about the UA check for old behavior, as it was added a long time ago and doesn't really apply to modern browsers. The UA check defaults to the latest rewriting if not present, but otherwise might choose the old method.
For reference, the UA check is here:
https://github.com/webrecorder/pywb/blob/master/pywb/rewrite/default_rewriter.py#L130

This should probably be disabled, or limited to only the known old browsers.
