### ISSUE TITLE
For ePub documents, show chapter and paragraph numbers when text is selected, for citation purposes.

### ISSUE THREAD

**Issue by anjackson** [ukwa/ukwa-pywb#98]
Our current solution shows the chapter and paragraph number when a section of text is highlighted in an ePub document. This is our recommended approach to citation, and must be supported by this new viewer.

The current solution looks like this:

![2022-10-07-epub-citation](https://user-images.githubusercontent.com/87843/195106811-7fb6f5f7-d31a-49cc-8449-2c782ff9cb8b.jpg)

The new solution does not have to look the same - it's just to give the idea.

Note that this citation proposal does not expose (and does not necessarily require) an implementation of the _EPUB Canonical Fragment Identifiers_.

**Comment by anjackson** [comment]
It's perhaps worth noting that recent versions of Calibre do not behave like this. You can enter 'Reference Mode' and then the `C.P` number is displayed at the start of each paragraph.

**Comment by anjackson** [comment]
Ah, I think we missed a bit @tw4l  - we also want to be able to use citations by searching for them. Apparently this works for the original user (I think it gets remembered in the session), but really we need some way for 'fresh' users to be able to search for a `X.N` reference.

It was also pointed out that the first number doesn't match the printed chapter number, but presumably that was the same for Calibre?!

**Comment by tw4l** [comment]
@anjackson Search result highlighting is now working for text string search queries (will demo Thursday), but I'm still working on highlighting entire paragraphs from a `X.N` reference - currently we just have the starting CFI for each paragraph, so I need to modify that so that we have a CFI range to be able to highlight the entire paragraph. This may not be ready by Thursday, but I will try to get it implemented as soon as possible after that.

**Comment by anjackson** [comment]
Thanks @tw4l 

I've tried to tidy up the PRs a bit to make things clearer. Please let me know if I've caused any problems.
